title: Denis Momanyi
email: econdenis@gmail.com
description: PhD Candidate | Agricultural Economics | Humboldt-Universität zu Berlin
twitter_username: deno_ec
github_username: deno-hub
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/Berlin

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author profile
author:
  name   : "Denis Momanyi"
  avatar : "/assets/IMG_20250718_143939.jpg"
  bio    : "PhD researcher in climate-smart agriculture, inequality, and smallholder resilience."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:econdenis@gmail.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://x.com/deno_ec"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/deno-hub"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=gRc0wP4AAAAJ&hl=en&oi=ao"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0003-3134-8651"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/denis-momanyi/"

# Footer icons
footer:
  links:
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=gRc0wP4AAAAJ&hl=en&oi=ao"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0003-3134-8651"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/denis-momanyi/"

# Page layouts and styles
sass:
  style: compressed

# Global defaults for pages and posts
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      custom_stylesheet: /assets/css/custom.css

  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      custom_stylesheet: /assets/css/custom.css

  - scope:
      path: ""
    values:
      custom_stylesheet: /assets/css/custom.css

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
