title: Denis Momanyi
email: denis.momanyi@hu-berlin.de
description: PhD Candidate | Agricultural Economics | Humboldt-Universität zu Berlin
twitter_username: deno_ec
github_username: deno-hub
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/Berlin

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Denis Momanyi"
  avatar : "/assets/images/bio-photo.jpg" # Replace with your photo path
  bio    : "PhD researcher in climate-smart agriculture, inequality, and smallholder resilience."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:denis.momanyi@hu-berlin.de"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://x.com/deno_ec"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/deno-hub"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=YOUR_ID"  # replace with your ID
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/YOUR_PROFILE/"  # replace with your profile

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://x.com/deno_ec"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/deno-hub"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=YOUR_ID"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
